{{- range $app := .Values.apps }}
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: {{ $app.appName }}-image-update
  namespace: flux-system
  labels:
    app: {{ $app.appName }}
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: {{ $.Values.chartsRepoName }}
  update:
    strategy: Setters
    path: "./apps/{{ $app.appName }}"
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
{{- end }}
