{{- $env := .Values.env | required ".Values.env is required." -}}

{{- range $app := .Values.apps }}
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: {{ $app.appName }}-{{ $.Values.env }}
  namespace: flux-system
  labels:
    app: {{ $app.appName }}
spec:
  imageRepositoryRef:
    name: {{ $app.appName }}-image-repo
  policy:
    {{ if eq $env "prod" }}
    semver:
      range: ">= 0.0.0"
    {{ else if eq $env "stg" }}
    filterTags:
      pattern: '.*-rc.*'
    policy:
      semver:
        range: '^1.x-0'
    {{ else }}
    filterTags:
      pattern: '^[a-fA-F0-9]+-(?P<ts>.*)'
      extract: '$ts'
    policy:
      numerical:
        order: asc

{{ end }}
{{ end }}