apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo-python-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: "./charts"
      sourceRef:
        kind: GitRepository
        name: demo-python-app
      valuesFiles:
        - ./charts/values.yaml
  interval: 1m
  # values:
  #   appVersion: v0.1.5  # {"$imagepolicy": "flux-system:demo-python-app:tag"}
